changelog:
  categories:
    - title: All features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - ignore-for-release
    - title: Dependencies
      labels:
        - dependencies
